# Generated by Django 6.0 on 2026-03-20 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challengesubmission',
            name='model_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challengesubmission',
            name='result',
            field=models.CharField(choices=[('correct', 'Correct'), ('partial', 'Partial'), ('incorrect', 'Incorrect')], default='partial', max_length=20),
        ),
        migrations.AddField(
            model_name='challengesubmission',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
