# Generated by Django 6.0 on 2026-02-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance_usd',
            field=models.FloatField(default=10000.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='btc_held',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_bot_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='rsi_threshold_buy',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='rsi_threshold_sell',
            field=models.IntegerField(default=70),
        ),
    ]
