# Generated by Django 6.0 on 2026-02-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_balance_usd_profile_btc_held_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance_usd',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='btc_held',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_bot_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rsi_threshold_buy',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rsi_threshold_sell',
        ),
    ]
