# Generated by Django 6.0 on 2026-02-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_balance_usd_remove_profile_btc_held_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
